import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Nav from "pages/Nav";
import Link from "next/link";
import { default as data } from "package.json";
const addonList = [
  "NPM, ",
  "GIT, ",
  "NextJs, ",
  "TailwindCSS, ",
  "Typescript, ",
  "Prettier, ",
  "ESlint, ",
  "Husky, ",
  "LintStaged, ",
  "Jest "
];
const date = new Date();
const seconds: number = date.getSeconds();
const minutes: number = date.getMinutes();
const hours: number = date.getHours();
const time = `${hours}:${minutes}:${seconds}`;
let timeWelcome = `${hours}:${minutes}`;

if (hours < 12 && hours > 5) {
  timeWelcome = "Good morning!";
} else if (hours > 5 && hours >= 12 && hours < 14) {
  timeWelcome = "Good afternoon!";
} else if (hours >= 14 && hours < 20) {
  timeWelcome = "Good evening!";
} else if (hours >= 20 && hours < 23) {
  timeWelcome = "Welcome, I hope your evening is well.";
} else {
  timeWelcome = "Ah, it's late! Night is always the most peaceful. Welcome.";
}
const Index: NextPage = () => (
  <div className="light:bg-white mx-auto bg-backgray ">
    <Nav />
    <Head>
      <meta name="description" content="Generated by create next app" />
      <title>{data.name}</title>
      <link rel="icon" href="/images/melongray.png" className="border" />
    </Head>

    <main className={styles.main}>
      <h1 className={styles.title}>{timeWelcome}</h1>
      <h2 className={styles.central}> This is my personal portfolio</h2>
      <div className={styles.description}>
        While currently studying as a senior at SUNY at Albany, I am currently
        working on my portfolio. I am a software engineer with a passion for
        learning and building things. Thomas Lloyd-Jones
        <div className="grid grid-cols-2">
          <p className={styles.descriptiondouble}>
            Before persuing my love of code, I have previously worked as a
            cosmetologist. I have a passion for creating and maintaining beauty
            in all of it&apos;s forms.
          </p>
          <p className={styles.descriptiondouble}>
            Before persuing my love of code, I have previously worked as a
            cosmetologist. I have a passion for creating and maintaining beauty
            in all of it&apos;s forms.
          </p>
        </div>
      </div>
    </main>

    <footer className={styles.footer}>
      <div className={styles.grid}>
        <p className="color-white left-0 m-4 max-w-xs border-spacing-4 border border-solid p-6 text-left">
          Powered by {addonList}
        </p>
        <h4 className="color-white right-0 m-4 max-w-xs border-spacing-4 border border-solid p-6 text-left">
          Thomas Lloyd-Jones
        </h4>
      </div>
      <p className="relative">
        <small className=" absolute inset-x-0 bottom-0">{time}</small>
      </p>
    </footer>
  </div>
);

export default Index;
